language: java
jdk:
  - oraclejdk8

before_script: 
  - git update-index --chmod=+x gradlew

install:
  - gradle assemble

script:
  - gradle check

deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_KEY"
  app: askinator
